import { useMemo, useState } from 'react';

const CHALLENGES=[
{id:'det',course:'Lineer Cebir',level:'Başlangıç',title:'Determinantı Bul',prompt:'A = [[3, 2], [1, 4]] matrisinin determinantı kaçtır?',hint:'2×2 matris için det(A)=ad-bc.',type:'number',answer:10,explain:'det(A)=3·4-2·1=12-2=10.'},
{id:'eigen',course:'Lineer Cebir',level:'Orta',title:'Özdeğeri Yakala',prompt:'A = [[2,0],[0,5]] matrisinin büyük özdeğeri nedir?',hint:'Köşegen matrisin özdeğerleri köşegen elemanlarıdır.',type:'number',answer:5,explain:'Özdeğerler 2 ve 5 olduğundan büyük olan 5’tir.'},
{id:'fourier',course:'Sinyaller ve Sistemler',level:'Başlangıç',title:'Temel Frekans',prompt:'Periyodu T=0.25 s olan sinyalin temel frekansı kaç Hz’dir?',hint:'f₀=1/T.',type:'number',answer:4,explain:'f₀=1/0.25=4 Hz.'},
{id:'ode',course:'Diferansiyel Denklemler',level:'Orta',title:'Kritik Sönüm',prompt:'m=1 ve k=9 için my″+cy′+ky=0 sistemini kritik sönümlü yapan c değeri nedir?',hint:'Kritik sönümde c=2√(mk).',type:'number',answer:6,explain:'c=2√(1·9)=6.'},
{id:'dfa',course:'Biçimsel Diller',level:'Orta',title:'01 ile Biten Dizgi',prompt:'Aşağıdakilerden hangisi 01 ile biten dizgiler diline aittir?',hint:'Sadece son iki sembole bak.',type:'choice',options:['1010','1101','0110','1111'],answer:'1101',explain:'1101 dizgisinin son iki sembolü 01’dir.'}
];
function grade(challenge,value){if(challenge.type==='number'){const n=Number(String(value).replace(',','.'));return Number.isFinite(n)&&Math.abs(n-challenge.answer)<1e-8}return value===challenge.answer}
export default function ChallengeTab(){const[index,setIndex]=useState(0);const[value,setValue]=useState('');const[result,setResult]=useState(null);const[score,setScore]=useState({correct:0,total:0});const c=CHALLENGES[index];const progress=useMemo(()=>Math.round((score.correct/Math.max(1,score.total))*100),[score]);const check=()=>{if(value==='')return;const ok=grade(c,value);setResult(ok);setScore(s=>({correct:s.correct+(ok?1:0),total:s.total+1}))};const next=()=>{setIndex(i=>(i+1)%CHALLENGES.length);setValue('');setResult(null)};return <div className="challenge-shell"><section className="challenge-top"><div><span className="lab-kicker">3.1 · Challenge Mode</span><h2>Problem Çözme Arenası</h2><p>Seviyeli mühendislik-matematik sorularını çöz; cevap anında tarayıcı içinde doğrulansın.</p></div><div className="challenge-score"><strong>{score.correct}/{score.total}</strong><span>Doğru · %{progress}</span></div></section><div className="challenge-grid"><aside className="challenge-list">{CHALLENGES.map((item,i)=><button key={item.id} className={i===index?'active':''} onClick={()=>{setIndex(i);setValue('');setResult(null)}}><span>{item.course}</span><strong>{item.title}</strong><small>{item.level}</small></button>)}</aside><article className="challenge-card"><div className="challenge-meta"><span>{c.course}</span><span>{c.level}</span></div><h2>{c.title}</h2><p className="challenge-prompt">{c.prompt}</p>{c.type==='choice'?<div className="challenge-options">{c.options.map(o=><button key={o} className={value===o?'selected':''} onClick={()=>setValue(o)}>{o}</button>)}</div>:<input className="challenge-answer" inputMode="decimal" placeholder="Cevabın" value={value} onChange={e=>setValue(e.target.value)}/>}<details className="challenge-hint"><summary>İpucu</summary><p>{c.hint}</p></details><div className="btn-row"><button className="btn btn-primary" onClick={check}>Cevabı Kontrol Et</button><button className="btn btn-secondary" onClick={next}>Sonraki →</button></div>{result!==null&&<div className={`challenge-feedback ${result?'correct':'wrong'}`}><strong>{result?'✓ Doğru':'✕ Tekrar dene'}</strong><p>{result?c.explain:'İpucunu kullanıp hesabı yeniden kontrol et. Cevap henüz gösterilmedi.'}</p></div>}</article></div></div>}
