import { useMemo, useState } from 'react';

const SEEDS=[
{id:'rlc-damped',title:'RLC Sönümlü Geçici Rejim',author:'SimuMath Labs',course:'Diferansiyel Denklemler',module:'ode',tags:['RLC','devre','geçici rejim'],description:'Seri RLC devresinin sönümlü cevabını inceleyen hazır çalışma.',hash:'#ode?type=rlc&t=20'},
{id:'pendulum-nonlinear',title:'Doğrusal Olmayan Sarkaç',author:'SimuMath Labs',course:'Diferansiyel Denklemler',module:'ode',tags:['sarkaç','nonlinear','faz portresi'],description:'Büyük açı davranışını zaman cevabı ve faz portresiyle karşılaştır.',hash:'#ode?type=pendulum&t=25'},
{id:'matrix-shear',title:'Shear ve Özvektör Sezgisi',author:'SimuMath Labs',course:'Lineer Cebir',module:'matrix',tags:['matrix','shear','eigen'],description:'Bir shear dönüşümünde koordinat ızgarası ve özvektör geometrisini keşfet.',hash:'#matrix?a=1&b=1&c=0&d=1&vx=1&vy=1'},
{id:'fourier-gibbs',title:'Gibbs Olayı',author:'SimuMath Labs',course:'Sinyaller ve Sistemler',module:'fourier',tags:['Fourier','Gibbs','square'],description:'Kare dalga yaklaşımında harmonik sayısının hata ve taşmaya etkisini gözle.',hash:'#fourier?wave=square&n=15'},
{id:'dfa-end01',title:'01 ile Biten Dizgiler',author:'SimuMath Labs',course:'Biçimsel Diller',module:'dfa',tags:['DFA','binary','automata'],description:'01 ile biten ikili dizgileri kabul eden otomata çalışması.',hash:'#dfa'},
];
const KEY='simumath:community-forks:v1';
function loadForks(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
function saveForks(items){localStorage.setItem(KEY,JSON.stringify(items))}
export default function CommunityTab(){const[query,setQuery]=useState('');const[course,setCourse]=useState('Tümü');const[forks,setForks]=useState(loadForks);const items=useMemo(()=>[...forks,...SEEDS],[forks]);const courses=['Tümü',...new Set(items.map(x=>x.course))];const filtered=useMemo(()=>items.filter(x=>(course==='Tümü'||x.course===course)&&(`${x.title} ${x.author} ${x.tags.join(' ')} ${x.description}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR')))),[items,query,course]);const open=item=>{window.location.hash=item.hash.replace(/^#/,'')};const fork=item=>{const copy={...item,id:`fork-${Date.now()}`,title:`${item.title} — Fork`,author:'Benim Koleksiyonum',forkedFrom:item.id,local:true};const next=[copy,...forks];setForks(next);saveForks(next)};const remove=id=>{const next=forks.filter(x=>x.id!==id);setForks(next);saveForks(next)};return <div className="community-shell"><section className="community-head"><div><span className="lab-kicker">3.4 · Community Showcase</span><h2>Topluluk Laboratuvarı</h2><p>Hazır simülasyonları keşfet, kendi kopyanı oluştur ve parametreleri değiştirerek yeni bir çalışma üret.</p></div><div className="community-count"><strong>{filtered.length}</strong><span>çalışma</span></div></section><section className="community-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Simülasyon, konu veya etiket ara…"/><div>{courses.map(c=><button key={c} className={course===c?'active':''} onClick={()=>setCourse(c)}>{c}</button>)}</div></section><section className="community-grid">{filtered.map(item=><article className="community-card" key={item.id}><div className="community-card-top"><span className="route-chip">#{item.module}</span>{item.local&&<span className="local-badge">Yerel fork</span>}</div><h3>{item.title}</h3><p>{item.description}</p><div className="community-meta"><span>{item.author}</span><span>{item.course}</span></div><div className="community-tags">{item.tags.map(t=><span key={t}>{t}</span>)}</div><div className="btn-row"><button className="btn btn-primary" onClick={()=>open(item)}>Laboratuvarı Aç</button><button className="btn btn-secondary" onClick={()=>fork(item)}>Forkla</button>{item.local&&<button className="btn btn-secondary" onClick={()=>remove(item.id)}>Sil</button>}</div>{item.forkedFrom&&<small>Fork kaynağı: {item.forkedFrom}</small>}</article>)}</section><section className="community-note"><strong>Yerel-first sürüm</strong><p>Forklanan çalışmalar bu cihazın localStorage alanında saklanır. Gerçek çok-kullanıcılı yayınlama, beğeni ve kullanıcı profilleri için ileride backend/auth katmanı eklenebilir.</p></section></div>}
