import { useMemo, useState } from 'react';
import { buildAutomaton, DFA_REGISTRY, NFA_REGISTRY, runAutomaton } from '../lib/dfa';

const VIEW=380,R=32;
const CUSTOM_DEFAULTS={dfa:{statesText:'Q0, Q1',alphabetText:'0, 1',start:'Q0',acceptText:'Q1',transitionsText:'Q0,0 -> Q0\nQ0,1 -> Q1\nQ1,0 -> Q0\nQ1,1 -> Q1'},nfa:{statesText:'S, A, F',alphabetText:'0, 1',start:'S',acceptText:'F',transitionsText:'S,0 -> S | A\nS,1 -> S\nA,1 -> F'}};
function mapPos(positions){const vals=Object.values(positions),xs=vals.map(v=>v[0]),ys=vals.map(v=>v[1]),minX=Math.min(...xs)-1.5,maxX=Math.max(...xs)+1.5,minY=Math.min(...ys)-1.5,maxY=Math.max(...ys)+1.5;return(x,y)=>[30+(x-minX)/(maxX-minX)*(VIEW-60),VIEW-(30+(y-minY)/(maxY-minY)*(VIEW-60))];}
function edgesOf(def){const out=[];for(const[key,dsts]of Object.entries(def.transitions)){const[src,symbol]=key.split(',');for(const dst of Array.isArray(dsts)?dsts:[dsts])out.push({src,dst,symbol});}return out;}

export default function DFATab(){
 const[kind,setKind]=useState('dfa'),[rule,setRule]=useState('ends_with_one'),[input,setInput]=useState('1011'),[step,setStep]=useState(0);
 const[custom,setCustom]=useState(CUSTOM_DEFAULTS.dfa),[customDef,setCustomDef]=useState(null),[editorError,setEditorError]=useState('');
 const registry=kind==='dfa'?DFA_REGISTRY:NFA_REGISTRY,def=rule==='custom'&&customDef?customDef:registry[rule]||Object.values(registry)[0];
 const result=useMemo(()=>runAutomaton(def,input),[def,input]),active=result.trace[Math.min(step,result.trace.length-1)]||[];
 const toScreen=useMemo(()=>mapPos(def.positions),[def]),edges=useMemo(()=>edgesOf(def),[def]);
 const changeKind=next=>{setKind(next);setRule(Object.keys(next==='dfa'?DFA_REGISTRY:NFA_REGISTRY)[0]);setCustom(CUSTOM_DEFAULTS[next]);setCustomDef(null);setEditorError('');setStep(0)};
 const applyCustom=()=>{try{const next=buildAutomaton({kind,...custom});setCustomDef(next);setRule('custom');setInput(value=>[...value].filter(ch=>next.alphabet.includes(ch)).join(''));setEditorError('');setStep(0)}catch(error){setEditorError(error.message)}};
 const setField=(key,value)=>setCustom(current=>({...current,[key]:value}));
 return <div className="tab-panel"><div className="control-panel"><h2>DFA / NFA Simülatörü</h2><div className="btn-row"><button className={`btn ${kind==='dfa'?'btn-primary':'btn-secondary'}`} onClick={()=>changeKind('dfa')}>DFA</button><button className={`btn ${kind==='nfa'?'btn-primary':'btn-secondary'}`} onClick={()=>changeKind('nfa')}>NFA</button></div>
 <div className="field"><label><span>Dil / Otomata</span></label><select value={rule} onChange={e=>{setRule(e.target.value);setStep(0)}}>{Object.values(registry).map(d=><option key={d.key} value={d.key}>{d.name}</option>)}{customDef&&<option value="custom">Özel {kind.toUpperCase()}</option>}</select></div><p className="description">{def.description}</p>
 <details className="custom-builder"><summary>Kendi {kind.toUpperCase()} otomatanı oluştur</summary><div className="field"><label><span>Durumlar</span></label><input value={custom.statesText} onChange={e=>setField('statesText',e.target.value)} placeholder="Q0, Q1, Q2"/></div><div className="field"><label><span>Alfabe</span></label><input value={custom.alphabetText} onChange={e=>setField('alphabetText',e.target.value)} placeholder="0, 1"/></div><div className="field"><label><span>Başlangıç durumu</span></label><input value={custom.start} onChange={e=>setField('start',e.target.value.trim())}/></div><div className="field"><label><span>Kabul durumları</span></label><input value={custom.acceptText} onChange={e=>setField('acceptText',e.target.value)} placeholder="Q1, Q2"/></div><div className="field"><label><span>Geçişler · NFA hedeflerini | ile ayır</span></label><textarea rows="7" value={custom.transitionsText} onChange={e=>setField('transitionsText',e.target.value)} placeholder={'Q0,0 -> Q0\nQ0,1 -> Q1'}/></div><button className="btn btn-secondary" onClick={applyCustom}>Otomatayı Uygula</button>{editorError&&<div className="result-banner" style={{color:'var(--accent-red)'}}>{editorError}</div>}</details>
 <div className="field"><label><span>String</span></label><input value={input} onChange={e=>{setInput([...e.target.value].filter(ch=>def.alphabet.includes(ch)).join(''));setStep(0)}} /></div><div className="progress-mono"><span style={{color:'var(--accent-teal)'}}>{input.slice(0,step)}</span><span style={{color:'var(--text-muted)'}}>{input.slice(step)}</span></div><div className="result-banner">Aktif durum kümesi: {'{'}{active.filter(Boolean).join(', ')||'∅'}{'}'}</div><div className="btn-row"><button className="btn btn-secondary" disabled={step===0} onClick={()=>setStep(s=>s-1)}>← Geri</button><button className="btn btn-primary" disabled={step>=result.trace.length-1} onClick={()=>setStep(s=>s+1)}>İleri →</button><button className="btn btn-secondary" onClick={()=>setStep(result.trace.length-1)}>Sona Git</button></div><div className="result-banner" style={{color:step===result.trace.length-1?(result.accepted?'var(--accent-teal)':'var(--accent-red)'):'var(--text-muted)'}}>{step===result.trace.length-1?(result.accepted?'KABUL EDİLDİ':'REDDEDİLDİ'):`Adım ${step}/${result.trace.length-1}`}</div>{kind==='nfa'&&<p className="description">NFA modunda aynı sembol sonrası birden fazla duruma dallanılabilir; aktif durum kümesi bunu canlı gösterir.</p>}</div>
 <div className="viz-panel"><div className="viz-title">{def.name}</div><div className="viz-body"><svg viewBox={`0 0 ${VIEW} ${VIEW}`} width="100%" style={{maxWidth:460}}><defs><marker id="auto-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#5b6b8c"/></marker></defs>{edges.map((e,i)=>{const[x1,y1]=toScreen(...def.positions[e.src]),[x2,y2]=toScreen(...def.positions[e.dst]);if(e.src===e.dst)return <g key={i}><path d={`M ${x1-15} ${y1-26} Q ${x1} ${y1-75} ${x1+15} ${y1-26}`} fill="none" stroke="#5b6b8c" markerEnd="url(#auto-arrow)"/><text x={x1} y={y1-60} fill="#e8ecf3" textAnchor="middle">{e.symbol}</text></g>;return <g key={i}><line x1={x1} y1={y1} x2={x2} y2={y2} stroke="#5b6b8c" markerEnd="url(#auto-arrow)"/><text x={(x1+x2)/2} y={(y1+y2)/2-6} fill="#e8ecf3" textAnchor="middle">{e.symbol}</text></g>})}{def.states.map(s=>{const[x,y]=toScreen(...def.positions[s]),on=active.includes(s);return <g key={s}><circle cx={x} cy={y} r={R} fill={on?'#e65b5b':'#f2a93b'} stroke="#0b1220" strokeWidth="2"/>{def.accept.has(s)&&<circle cx={x} cy={y} r={R-6} fill="none" stroke="#0b1220"/>}<text x={x} y={y+5} textAnchor="middle" fontWeight="700">{s}</text></g>})}</svg></div></div></div>;
}
