import { useMemo, useRef, useState } from 'react';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const MAX_SAMPLES = 512;
function spectrum(samples, sampleRate) {
  const n = Math.min(samples.length, 256); if (n < 16) return [];
  const x = samples.slice(-n); const mean = x.reduce((a,b)=>a+b,0)/n;
  const bins = [];
  for (let k=1;k<=Math.min(48,Math.floor(n/2));k++) { let re=0, im=0; for(let i=0;i<n;i++){const a=2*Math.PI*k*i/n; const v=x[i]-mean; re+=v*Math.cos(a); im-=v*Math.sin(a);} bins.push({ frequency: +(k*sampleRate/n).toFixed(2), amplitude: +(2*Math.hypot(re,im)/n).toFixed(5) }); }
  return bins;
}
function numberFromLine(line) { const parts=line.trim().split(/[;,\s]+/).map(Number).filter(Number.isFinite); return parts.length ? parts[parts.length-1] : null; }

export default function HardwareTab(){
  const [samples,setSamples]=useState([]); const [sampleRate,setSampleRate]=useState(100); const [status,setStatus]=useState('Bağlı değil'); const [baud,setBaud]=useState(115200); const [serviceUuid,setServiceUuid]=useState(''); const [charUuid,setCharUuid]=useState('');
  const portRef=useRef(null); const readerRef=useRef(null); const bleCharRef=useRef(null); const timerRef=useRef(null);
  const chart=useMemo(()=>samples.slice(-256).map((v,i)=>({i,value:v})),[samples]); const fft=useMemo(()=>spectrum(samples,sampleRate),[samples,sampleRate]); const peak=useMemo(()=>fft.reduce((best,x)=>!best||x.amplitude>best.amplitude?x:best,null),[fft]);
  const push=(v)=>setSamples(s=>[...s,v].slice(-MAX_SAMPLES));
  async function connectSerial(){ if(!('serial' in navigator)){setStatus('Web Serial desteklenmiyor');return;} try{const port=await navigator.serial.requestPort(); await port.open({baudRate:Number(baud)}); portRef.current=port; setStatus('Serial bağlı'); const decoder=new TextDecoder(); let buffer=''; const reader=port.readable.getReader(); readerRef.current=reader; while(true){const{value,done}=await reader.read(); if(done)break; buffer+=decoder.decode(value,{stream:true}); const lines=buffer.split(/\r?\n/); buffer=lines.pop()||''; for(const line of lines){const v=numberFromLine(line); if(v!==null)push(v);}} }catch(e){setStatus(e?.name==='NotFoundError'?'Port seçilmedi':`Serial hata: ${e.message}`);} finally{readerRef.current?.releaseLock?.(); readerRef.current=null;} }
  async function disconnectSerial(){try{await readerRef.current?.cancel(); await portRef.current?.close();}catch{} portRef.current=null; setStatus('Bağlı değil');}
  async function connectBluetooth(){ if(!navigator.bluetooth){setStatus('Web Bluetooth desteklenmiyor');return;} if(!serviceUuid||!charUuid){setStatus('BLE service ve characteristic UUID gerekli');return;} try{const device=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[serviceUuid]}); const server=await device.gatt.connect(); const service=await server.getPrimaryService(serviceUuid); const characteristic=await service.getCharacteristic(charUuid); await characteristic.startNotifications(); const handler=(e)=>{const view=e.target.value; let v=null; if(view.byteLength===4)v=view.getFloat32(0,true); else {const text=new TextDecoder().decode(view); v=numberFromLine(text);} if(Number.isFinite(v))push(v);}; characteristic.addEventListener('characteristicvaluechanged',handler); bleCharRef.current={characteristic,handler,device}; device.addEventListener('gattserverdisconnected',()=>setStatus('BLE bağlantısı kesildi')); setStatus(`BLE bağlı${device.name?` · ${device.name}`:''}`);}catch(e){setStatus(`BLE hata: ${e.message}`);} }
  async function disconnectBluetooth(){const ref=bleCharRef.current; if(ref){try{ref.characteristic.removeEventListener('characteristicvaluechanged',ref.handler); await ref.characteristic.stopNotifications(); ref.device.gatt?.disconnect();}catch{}} bleCharRef.current=null; setStatus('Bağlı değil');}
  function demo(){clearInterval(timerRef.current); let i=0; setSamples([]); timerRef.current=setInterval(()=>{push(Math.sin(2*Math.PI*5*i/sampleRate)+0.35*Math.sin(2*Math.PI*12*i/sampleRate)+(Math.random()-.5)*.08);i++; if(i>1500){clearInterval(timerRef.current);timerRef.current=null;}},1000/sampleRate); setStatus('Demo sensör akışı');}
  return <div className="hardware-layout"><section className="control-panel"><span className="lab-kicker">2.3 · Hardware Lab</span><h2>ESP32 / Arduino Canlı Veri</h2><p className="description">USB Serial veya BLE üzerinden satır başına tek sayısal sensör değeri al; zaman alanını ve Fourier spektrumunu canlı incele.</p><div className="result-banner">{status}</div><div className="field"><label><span>Örnekleme hızı (Hz)</span></label><input type="number" min="1" max="5000" value={sampleRate} onChange={e=>setSampleRate(Math.max(1,+e.target.value||1))}/></div><div className="field"><label><span>Serial baud</span></label><select value={baud} onChange={e=>setBaud(+e.target.value)}><option>9600</option><option>57600</option><option>115200</option><option>230400</option><option>460800</option></select></div><div className="btn-row" style={{flexWrap:'wrap'}}><button className="btn btn-primary" onClick={connectSerial}>USB Serial Bağla</button><button className="btn btn-secondary" onClick={disconnectSerial}>Serial Kes</button></div><div className="field"><label><span>BLE Service UUID</span></label><input value={serviceUuid} onChange={e=>setServiceUuid(e.target.value.trim())} placeholder="örn. 12345678-..."/></div><div className="field"><label><span>BLE Characteristic UUID</span></label><input value={charUuid} onChange={e=>setCharUuid(e.target.value.trim())} placeholder="örn. 87654321-..."/></div><div className="btn-row" style={{flexWrap:'wrap'}}><button className="btn btn-primary" onClick={connectBluetooth}>Bluetooth Bağla</button><button className="btn btn-secondary" onClick={disconnectBluetooth}>BLE Kes</button></div><div className="btn-row"><button className="btn btn-secondary" onClick={demo}>Demo Sinyal</button><button className="btn btn-secondary" onClick={()=>setSamples([])}>Temizle</button></div><div className="result-banner">Örnek: <strong>{samples.length}</strong>{peak&&<> · Baskın frekans: <strong>{peak.frequency} Hz</strong></>}</div></section><section className="hardware-viz"><div className="viz-panel"><div className="viz-title">Canlı Zaman Alanı</div><div style={{height:300}}><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid stroke="#263758" strokeDasharray="3 3"/><XAxis dataKey="i"/><YAxis/><Tooltip/><Line dataKey="value" type="monotone" dot={false} stroke="#3ecf8e" strokeWidth={1.7}/></LineChart></ResponsiveContainer></div></div><div className="viz-panel"><div className="viz-title">Canlı Fourier Spektrumu</div><div style={{height:300}}><ResponsiveContainer width="100%" height="100%"><BarChart data={fft}><CartesianGrid stroke="#263758" strokeDasharray="3 3"/><XAxis dataKey="frequency"/><YAxis/><Tooltip/><Bar dataKey="amplitude" fill="#a66bff"/></BarChart></ResponsiveContainer></div></div></section></div>;
}
