import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import './App.css';
import './intuition.css';
const ODETab=lazy(()=>import('./components/ODETab'));const LinAlgTab=lazy(()=>import('./components/LinAlgTab'));const FourierTab=lazy(()=>import('./components/FourierTab'));const NetworkTab=lazy(()=>import('./components/NetworkTab'));const DFATab=lazy(()=>import('./components/DFATab'));const NotebookTab=lazy(()=>import('./components/NotebookTab'));const AssistantTab=lazy(()=>import('./components/AssistantTab'));const HardwareTab=lazy(()=>import('./components/HardwareTab'));const ChallengeTab=lazy(()=>import('./components/ChallengeTab'));
const CHANNELS=[{key:'ode',code:'ODE',label:'Diferansiyel Denklemler',description:'Dinamik sistemleri RK4 ile simüle et.',Component:ODETab},{key:'matrix',code:'MTX',label:'Lineer Cebir & Özvektörler',description:'Matris davranışını ve özvektörleri görselleştir.',Component:LinAlgTab},{key:'fourier',code:'SER',label:'Fourier Serileri',description:'Harmoniklerle sinyal sentezini keşfet.',Component:FourierTab},{key:'network',code:'NET',label:'Ağ Yönlendirme (Dijkstra)',description:'En kısa yolu grafik üzerinde adım adım incele.',Component:NetworkTab},{key:'dfa',code:'DFA',label:'Sonlu Otomata',description:'DFA/NFA kurallarını çalıştır ve durum geçişlerini izle.',Component:DFATab},{key:'notebook',code:'NBK',label:'Çalışma Kağıdı',description:'Markdown ve formül hücreleriyle interaktif laboratuvar raporu hazırla.',Component:NotebookTab},{key:'assistant',code:'AI',label:'Akıllı Simülasyon',description:'Doğal dildeki isteği simülasyona çevir ve parametre hatalarını analiz et.',Component:AssistantTab},{key:'hardware',code:'HW',label:'ESP32 / Arduino',description:'Web Serial ve Bluetooth ile canlı sensör verisini Fourier analizine bağla.',Component:HardwareTab},{key:'challenge',code:'CHL',label:'Challenge Mode',description:'Seviyeli problemleri çöz ve cevabını anında doğrula.',Component:ChallengeTab}];
const LEGACY_KEYS={linalg:'matrix'};
function parseRoute(){const raw=window.location.hash.replace(/^#\/?/,'');const [route,query='']=raw.split('?');const key=LEGACY_KEYS[route]||route;return{key:CHANNELS.some(c=>c.key===key)?key:'ode',params:new URLSearchParams(query)}}
function getChannelFromHash(){return parseRoute().key}
function App(){const[active,setActive]=useState(getChannelFromHash);const[copied,setCopied]=useState(false);const current=useMemo(()=>CHANNELS.find(c=>c.key===active)||CHANNELS[0],[active]);const ActiveComponent=current.Component;const embedded=parseRoute().params.get('embed')==='1';useEffect(()=>{const f=()=>setActive(getChannelFromHash());window.addEventListener('hashchange',f);if(!window.location.hash)window.history.replaceState(null,'','#ode');return()=>window.removeEventListener('hashchange',f)},[]);const openChannel=key=>{window.location.hash=key;setActive(key)};const copyLink=async()=>{try{await navigator.clipboard.writeText(window.location.href);setCopied(true);window.setTimeout(()=>setCopied(false),1600)}catch{setCopied(false)}};return <div className={`app-shell ${embedded?'embed-mode':''}`}>{!embedded&&<><header className="app-header"><div><span className="eyebrow">SimuMath Pro — Interactive Lab</span><h1>Denklemden diyagrama, tek laboratuvarda.</h1><p className="slogan">Sayısal yöntemleri, algoritmaları ve matematiksel sistemleri canlı olarak deneyimle.</p></div><button className="btn btn-secondary share-btn" onClick={copyLink}>{copied?'Bağlantı kopyalandı':'Bu laboratuvarı paylaş'}</button></header><section className="lab-status"><div><span className="lab-kicker">Aktif modül · {current.code}</span><strong>{current.label}</strong><p>{current.description}</p></div><span className="route-chip">#{current.key}</span></section><nav className="channel-selector">{CHANNELS.map(c=><button key={c.key} className={`channel-btn ${active===c.key?'active':''}`} onClick={()=>openChannel(c.key)}><span className="led"/><span className="code">{c.code}</span><span className="label">{c.label}</span></button>)}</nav></>}<main><Suspense fallback={<div className="module-loading">Laboratuvar yükleniyor…</div>}><ActiveComponent/></Suspense></main>{!embedded&&<footer className="footer-note">SimuMath Pro Web · React tabanlı interaktif mühendislik matematiği laboratuvarı.</footer>}</div>}
export default App;
